project:
  type: website
  execute-dir: project
  resources: [
   scripts,
   dataset_for_shiny
  ]

website:
  title: "MA [46]15 Final Project"
  navbar:
    right:
      - about.qmd
      - big_picture.qmd
      - analysis.qmd
      - data.qmd
format:
  html:
    theme: cosmo
    css: styles.css



